export const DIGITAL_CARD_REQUEST = 'DIGITAL_CARD_REQUEST';
export const DIGITAL_CARD_SUCCESS = 'DIGITAL_CARD_SUCCESS';
export const DIGITAL_CARD_FAIL = 'DIGITAL_CARD_FAIL';

export const DIGITAL_CARD_DETAILS_REQUEST = 'DIGITAL_CARD_DETAILS_REQUEST';
export const DIGITAL_CARD_DETAILS_SUCCESS = 'DIGITAL_CARD_DETAILS_SUCCESS';
export const DIGITAL_CARD_DETAILS_FAIL = 'DIGITAL_CARD_DETAILS_FAIL';
